default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: password
  database: app_development
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

test:
  <<: *default
  username: root
  password: password
  database: app_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
