services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./frontend:/app:cached
      - front_node_modules:/app/node_modules
    command: yarn dev -p 4000
    ports:
      - "4000:4000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/app:cached
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  front_node_modules:
  bundle_cache:
  postgres_data: