version: '3'
services:
  backend:
    user: vscode
    volumes:
      - ..:/app:cached
      - backend_node_modules:/app/node_modules
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: sleep infinity
    
  frontend:
    user: vscode
    volumes:
      - ..:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sleep infinity

volumes:
  backend_node_modules:
  frontend_node_modules:
  bundle_cache: